selftests/bpf: Clarify build error if no vmlinux
Summary:
selftests/bpf: Clarify build error if no vmlinux

If Makefile cannot find any of the vmlinux's in its VMLINUX_BTF_PATHS list,
it tries to run btftool incorrectly, with VMLINUX_BTF unset:

bpftool btf dump file $(VMLINUX_BTF) format c

Such that the keyword 'format' is misinterpreted as the path to vmlinux.
The resulting build error message is fairly cryptic:

GEN      vmlinux.h
Error: failed to load BTF from format: No such file or directory

This patch makes the failure reason clearer by yielding this instead:

Makefile:...: *** Cannot find a vmlinux for VMLINUX_BTF at any of
"{paths}".  Stop.


(cherry picked from commit 1a3449c19407a28f7019a887cdf0d6ba2444751a)

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes: acbd06206bbb ("selftests/bpf: Add vmlinux.h selftest exercising tracing of syscalls")
Signed-off-by: Kamal Mostafa <kamal@canonical.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Link: https://lore.kernel.org/bpf/20201215182011.15755-1-kamal@canonical.com