Enable config options to support external module driver builds
Summary:
enable config to fix broken Zion and main build

CONFIG_BACKLIGHT_CLASS_DEVICE required for amdgpu driver:

/root/rpmbuild/BUILD/amdgpu-kmod-5.11.32-1350682-fbk1/usr/src/amdgpu-5.11.32-1350682.el8/amd/amdgpu/atombios_encoders.c:256:6: error: conflicting types for 'amdgpu_atombios_encoder_init_backlight'

CONFIG_NEW_LEDS=y
CONFIG_LEDS_CLASS=m

Required for darwin_bsp

ERROR: modpost: "led_classdev_register_ext" [/rw/BUILD/darwin_bsp-1.1.0/drivers/rook-fan-cpld.ko] undefined!
ERROR: modpost: "led_classdev_unregister" [/rw/BUILD/darwin_bsp-1.1.0/drivers/rook-fan-cpld.ko] undefined!
ERROR: modpost: "devm_led_classdev_register_ext" [/rw/BUILD/darwin_bsp-1.1.0/drivers/scd-leds.ko] undefined!

CONFIG_MAX1363 required for FBOSS drivers

Test Plan: build regular and zion kernel

Reviewers: dylany, dsj, dmm, #linux_kernel

Reviewed By: dmm

Subscribers: ps, tulloch, jkkm

Differential Revision: https://phabricator.intern.facebook.com/D35064007