[FB-Only] fix build failure due to reassigning global 'DEBUG_OPTIONS'
Summary:
  Current `kf sandcastle <branch>` failed with the error:
    ERROR: /.../facebook/config/defs.bzl:7:1: cannot reassign global 'DEBUG_OPTIONS' ...
    ERROR: /.../facebook/config/defs.bzl:1:44: 'DEBUG_OPTIONS' previously declared here
    ERROR: /.../facebook/config/defs.bzl:8:1: cannot reassign global 'FLAVORS' ...
    ERROR: /.../facebook/config/defs.bzl:2:25: 'FLAVORS' previously declared here
  Fixed the issue to avoid use the same global variable names.

Test Plan:
  After the change, build is successful.
  $ kf sandcastle --revision 'origin/yhs/5.6-backport'
  https://www.internalfb.com/intern/sandcastle/job/22517998433359079/

Reviewers: #kernel_ops

Subscribers:

Tasks: T69829675

Tags:

Blame Revision:

Differential Revision: https://phabricator.intern.facebook.com/D22478519