kbuild: Skip module BTF generation for out-of-tree external modules
Summary:
In some modes of operation, Kbuild allows to build modules without having
vmlinux image around. In such case, generation of module BTF is impossible.
This patch changes the behavior to emit a warning about impossibility of
generating kernel module BTF, instead of breaking the build. This is especially
important for out-of-tree external module builds.

In vmlinux-less mode:

$ make clean
$ make modules_prepare
$ touch drivers/acpi/button.c
$ make M=drivers/acpi
...
  CC [M]  drivers/acpi/button.o
  MODPOST drivers/acpi/Module.symvers
  LD [M]  drivers/acpi/button.ko
  BTF [M] drivers/acpi/button.ko
Skipping BTF generation for drivers/acpi/button.ko due to unavailability of vmlinux
...
$ readelf -S ~/linux-build/default/drivers/acpi/button.ko | grep BTF -A1
... empty ...

Now with normal build:

$ make all
...
LD [M]  drivers/acpi/button.ko
BTF [M] drivers/acpi/button.ko
...
$ readelf -S ~/linux-build/default/drivers/acpi/button.ko | grep BTF -A1
  [60] .BTF              PROGBITS         0000000000000000  00029310
       000000000000ab3f  0000000000000000           0     0     1

Fixes: 5f9ae91f7c0d ("kbuild: Build kernel module BTFs if BTF is enabled and pahole supports it")
Reported-by: Bruce Allan <bruce.w.allan@intel.com>
Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Cc: Jessica Yu <jeyu@kernel.org>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
Link: https://lore.kernel.org/bpf/20201121070829.2612884-1-andrii@kernel.org
(cherry picked from commit e732b538f4557cd0a856bbce3cde55d2dfef3b03)

 # Conflicts:
 #	scripts/Makefile.modfinal

Test Plan:
Sandcastle builds. Local build fails with:

```
make[2]: *** [fs/notify] Error 2
make[2]: *** Waiting for unfinished jobs....
/data/users/andriin/linux-fb/fs/buffer.c: In function ‘alloc_page_buffers’:
/data/users/andriin/linux-fb/fs/buffer.c:866:14: error: implicit declaration of function ‘set_active_memcg’ [-Werror=implicit-function-declaration]
  866 |  old_memcg = set_active_memcg(memcg);
      |              ^~~~~~~~~~~~~~~~
/data/users/andriin/linux-fb/fs/buffer.c:866:12: warning: assignment to ‘struct mem_cgroup *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  866 |  old_memcg = set_active_memcg(memcg);
      |            ^
cc1: some warnings being treated as errors
make[2]: *** [fs/buffer.o] Error 1
```

Reviewers: songliubraving, ast, siudin

Reviewed By: songliubraving

Subscribers: ps, tulloch, jkkm

Differential Revision: https://phabricator.intern.facebook.com/D26236930

Tasks: T83354448

Signature: 26236930:1612395082:d83cabc6e7857df8d42b00ab7a829610a6dcb56f